package br.ulbra.view;

import br.ulbra.controller.ChamadoController;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ChamadoView extends javax.swing.JFrame {

    /**
     * Creates new form ChamadoView
     */
    public ChamadoView() {
        initComponents();
        listarTabela();
    }

    ChamadoController controller = new ChamadoController();

    public void listarTabela() {

        DefaultTableModel model = (DefaultTableModel) tblChamado.getModel();
        model.setRowCount(0);

        controller.listar().forEach((u) -> {
            model.addRow(new Object[]{
                u.getId(),
                u.getSolicitante(),
                u.getSala(),
                u.getEquipamentoTag(),
                u.getProblemaRelatado(),
                u.getDiagnosticoTecnico(),
                u.getPrioridade(),
                u.getStatus(),
                u.getDataAbertura()
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEquipamento = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtSala = new javax.swing.JTextField();
        txtProblema = new javax.swing.JTextField();
        txtDiagnostico = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtPrioridade = new javax.swing.JComboBox<>();
        txtStatus = new javax.swing.JComboBox<>();
        btnEnviar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChamado = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtSolicitante = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuChamado = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenuItem();
        menuEquipamento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtEquipamento.setBorder(javax.swing.BorderFactory.createTitledBorder("EQUIPAMENTO"));
        txtEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEquipamentoActionPerformed(evt);
            }
        });

        txtId.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtSala.setBorder(javax.swing.BorderFactory.createTitledBorder("SALA"));
        txtSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaActionPerformed(evt);
            }
        });

        txtProblema.setBorder(javax.swing.BorderFactory.createTitledBorder("PROBLEMA"));
        txtProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProblemaActionPerformed(evt);
            }
        });

        txtDiagnostico.setBorder(javax.swing.BorderFactory.createTitledBorder("DIAGNOSTICO"));
        txtDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiagnosticoActionPerformed(evt);
            }
        });

        txtData.setBorder(javax.swing.BorderFactory.createTitledBorder("DATA"));
        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        txtPrioridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BAIXA", "MEDIA", "ALTA" }));
        txtPrioridade.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PENDENTE", "COMPLETA" }));

        btnEnviar.setText("ENVIAR");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        tblChamado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "SOLICITANTE", "EQUIPAMENTO", "SALA", "PROBLEMA", "DIAGNOSTICO", "DATA", "PRIORIDADE", "STATUS"
            }
        ));
        jScrollPane1.setViewportView(tblChamado);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("CADASTRO CHAMADO");

        txtSolicitante.setBorder(javax.swing.BorderFactory.createTitledBorder("SOLICITANTE"));
        txtSolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSolicitanteActionPerformed(evt);
            }
        });

        jMenu1.setText("CADASTROS");

        menuChamado.setText("CHAMADO");
        menuChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChamadoActionPerformed(evt);
            }
        });
        jMenu1.add(menuChamado);

        menuUsuario.setText("USUARIO");
        jMenu1.add(menuUsuario);

        menuEquipamento.setText("EQUIPAMENTO");
        jMenu1.add(menuEquipamento);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("SOBRE");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(btnEnviar)
                .addGap(67, 67, 67)
                .addComponent(btnEditar)
                .addGap(80, 80, 80)
                .addComponent(btnExcluir)
                .addGap(67, 67, 67)
                .addComponent(btnLimpar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSala, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDiagnostico, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(txtPrioridade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(txtStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154)
                        .addComponent(txtEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(266, 266, 266))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProblema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnLimpar))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblChamadoMouseClicked(java.awt.event.MouseEvent evt) {                                        
        int linha = tblChamado.getSelectedRow();
        txtId.setText(tblChamado.getValueAt(linha, 0).toString());
        txtSolicitante.setText(tblChamado.getValueAt(linha, 1).toString());
        txtSala.setText(tblChamado.getValueAt(linha, 2).toString());
        txtEquipamento.setText(tblChamado.getValueAt(linha, 3).toString());
        txtProblema.setText(tblChamado.getValueAt(linha, 4).toString());
        txtDiagnostico.setText(tblChamado.getValueAt(linha, 5).toString());
        txtPrioridade.setSelectedItem(tblChamado.getValueAt(linha, 6).toString());
        txtStatus.setSelectedItem(tblChamado.getValueAt(linha, 7).toString());
        txtData.setText(tblChamado.getValueAt(linha, 8).toString());

    }
      
    private void txtEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEquipamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEquipamentoActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaActionPerformed

    private void txtProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProblemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProblemaActionPerformed

    private void txtDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiagnosticoActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void txtSolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSolicitanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSolicitanteActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        try {
            String strData = txtData.getText();
            java.text.SimpleDateFormat formatador = new java.text.SimpleDateFormat("dd/MM/yyyy");

            // 1. Cria a data normal (util)
            java.util.Date dataUtil = formatador.parse(strData);

            // 2. CONVERSÃƒO CRUCIAL: Transforma util.Date em sql.Date
            java.sql.Date dataSql = new java.sql.Date(dataUtil.getTime());

            // 3. Agora passe 'dataSql' para o seu controller
            String mensagem = controller.cadastrar(
                    txtSolicitante.getText(),
                    txtSala.getText(),
                    txtEquipamento.getText(),
                    txtProblema.getText(),
                    txtDiagnostico.getText(),
                    txtPrioridade.getSelectedItem().toString(),
                    txtStatus.getSelectedItem().toString(),
                    dataSql
            );

            javax.swing.JOptionPane.showMessageDialog(null, mensagem);
            listarTabela();

        } catch (java.text.ParseException e) {
            JOptionPane.showMessageDialog(null, "Formato de data invÃ¡lido! Use dd/MM/yyyy.");
        } catch (HeadlessException e) { // Isso ajuda a ver o erro real no console do NetBeans
            // Isso ajuda a ver o erro real no console do NetBeans
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtId.setText(null);
        txtSolicitante.setText(null);
        txtSala.setText(null);
        txtEquipamento.setText(null);
        txtProblema.setText(null);
        txtDiagnostico.setText(null);
        txtData.setText(null);
        txtPrioridade.setSelectedItem("BAIXA");
        txtStatus.setSelectedItem("PENDENTE");
        txtId.setFocusable(true);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null,
                "Deseja excluir o chamado ?", "ExclusÃ£o", JOptionPane.YES_NO_OPTION);
        Long id = Long.parseLong(txtId.getText());
        if (confirm == JOptionPane.YES_OPTION) {
            String msg = controller.deletar(id);
            JOptionPane.showMessageDialog(null, msg);
            listarTabela();
        } else {
            JOptionPane.showMessageDialog(null, "OperaÃ§Ã£o cancelada!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       Long id = Long.parseLong(txtId.getText());
        try {
            String strData = txtData.getText();
            java.text.SimpleDateFormat formatador = new java.text.SimpleDateFormat("dd/MM/yyyy");

            // 1. Cria a data normal (util)
            java.util.Date dataUtil = formatador.parse(strData);

            // 2. CONVERSÃƒO CRUCIAL: Transforma util.Date em sql.Date
            java.sql.Date dataSql = new java.sql.Date(dataUtil.getTime());

            // 3. Agora passe 'dataSql' para o seu controller
            String mensagem = controller.atualizar(
                    id,
                    txtSolicitante.getText(),
                    txtSala.getText(),
                    txtEquipamento.getText(),
                    txtProblema.getText(),
                    txtDiagnostico.getText(),
                    txtPrioridade.getSelectedItem().toString(),
                    txtStatus.getSelectedItem().toString(),
                    dataSql // <--- Use a dataSql aqui
            );

            javax.swing.JOptionPane.showMessageDialog(null, mensagem);
            listarTabela();

        } catch (java.text.ParseException e) {
            JOptionPane.showMessageDialog(null, "Formato de data invÃ¡lido! Use dd/MM/yyyy.");
        } catch (HeadlessException e) { // Isso ajuda a ver o erro real no console do NetBeans
           // Isso ajuda a ver o erro real no console do NetBeans
            JOptionPane.showMessageDialog(null, "Erro ao atualizar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void menuChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChamadoActionPerformed
        ChamadoView chamadoView = new ChamadoView();

        chamadoView.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_menuChamadoActionPerformed

    private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {                                            
        UsuarioView usuarioView = new UsuarioView();

        usuarioView.setVisible(true);

        this.dispose();
    }                                           

    private void menuEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {                                                
        EquipamentoView equipamentoView = new EquipamentoView();

        equipamentoView.setVisible(true);

        this.dispose();
    } 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChamadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChamadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChamadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChamadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ChamadoView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuChamado;
    private javax.swing.JMenuItem menuEquipamento;
    private javax.swing.JMenuItem menuUsuario;
    private javax.swing.JTable tblChamado;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDiagnostico;
    private javax.swing.JTextField txtEquipamento;
    private javax.swing.JTextField txtId;
    private javax.swing.JComboBox<String> txtPrioridade;
    private javax.swing.JTextField txtProblema;
    private javax.swing.JTextField txtSala;
    private javax.swing.JTextField txtSolicitante;
    private javax.swing.JComboBox<String> txtStatus;
    // End of variables declaration//GEN-END:variables
}
